#!/bin/sh
chown root:wheel /Library/LaunchDaemons/com.imokhles.nosandxdlaunch.plist
chmod 644 /Library/LaunchDaemons/com.imokhles.nosandxdlaunch.plist

chmod 4755 /usr/libexec/nosandxd
chown root:wheel /usr/libexec/nosandxd

launchctl load /Library/LaunchDaemons/com.imokhles.nosandxdlaunch.plist
exit 0